name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install -g http-server

    - name: Deploy
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        git checkout --orphan gh-pages
        git --work-tree . add --all
        git --work-tree . commit -m "Deploy to GitHub Pages"
        git push origin HEAD:gh-pages --force
        rm -rf .git
        git checkout main
        git branch -D gh-pages

    - name: Cleanup
      if: always()
      run: |
        git checkout main || true
        git branch -D gh-pages || true
